cd ~/yho-stack

# create a fly.toml inside api/ so the build context is api/
cat > api/fly.toml <<'EOF'
app = "yho-stack-api"

[env]
  PORT = "8000"
  DATA_DIR = "/data"

[mounts]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 1
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
EOF
